// End-to-end regression on a real-anonymized Novatek NVT-IM single-camera MOV.
// Media is regenerated by scripts/anonymize-mp4.mjs; the original local-as-UTC
// creation time and two allowlisted PWRS/ACC/PwrKey blocks are preserved. The
// source clip has no GPS records: its `freeGPS` markers contain status text
// plus zeros. The related GPS hardware variant keeps the embedded probe, so
// these blocks must be rejected without inventing fixes.

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { deriveStartUtc } from "../../../trips.js";
import { cameraFingerprint } from "../../camera-fingerprint.js";
import { classifyGpsSource, shouldTryEmbeddedGps } from "../../gps-source-hints.js";
import { buildMp4Index } from "../../internal/mp4-index.js";
import { indexMp4FileWithMoov } from "../../internal/mp4-indexing.js";
import {
    classifyFilenameTime,
    matchFilenameChannel,
    matchFilenameMode,
    matchFilenameSequence,
    matchFilenameTime,
} from "../../filename/index.js";
import { freegpsPrimitive } from "../../primitives/freegps.js";
import { WrongFormatError, type VendorFile } from "../../types.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const NAME = "2026_0809_222334_654A.MOV";

function loadFixture(): VendorFile {
    const bytes = readFileSync(resolve(HERE, "real-anonymized.MOV"));
    return {
        file: new File([bytes], NAME),
        relativePath: `MOVIE/${NAME}`,
    };
}

describe("real-anonymized Novatek NVT-IM MOV-A fixture", () => {
    it("classifies every filename capability and keeps the Novatek GPS probe", () => {
        const file = loadFixture();

        expect(matchFilenameTime(file)).toEqual({
            matchedId: "novatek-single-time",
            value: new Date("2026-08-09T22:23:34.000Z"),
        });
        expect(matchFilenameChannel(file)).toEqual({
            matchedId: "novatek-single-channel",
            value: { channel: "front", confident: true },
        });
        expect(matchFilenameMode(file)).toEqual({ matchedId: "novatek-mode", value: "normal" });
        expect(matchFilenameSequence(file)).toEqual({ matchedId: "novatek-sequence", value: 654 });
        expect(cameraFingerprint(file)).toBe("novatek-single|MOVIE|#_#_#_#A.MOV");
        expect(classifyGpsSource(file)).toBe("embedded");
        expect(shouldTryEmbeddedGps(file, false)).toBe(true);
    });

    it("indexes the real-derived timestamp and interprets it in the browser zone", async () => {
        const file = loadFixture();
        const { indexed } = await indexMp4FileWithMoov(file.file, false);
        expect(indexed).not.toBeNull();
        expect(indexed!.durationSec).toBe(2);
        expect(indexed!.createdUtc?.toISOString()).toBe("2026-08-09T22:23:36.000Z");
        expect(indexed!.codec).toBe("avc");
        expect(indexed!.codecParam).toBe("avc1");
        expect(indexed!.width).toBe(1920);
        expect(indexed!.height).toBe(1080);
        expect(indexed!.fps).toBeCloseTo(30, 6);

        const previousTz = process.env.TZ;
        process.env.TZ = "Europe/Samara";
        try {
            const result = deriveStartUtc({
                file,
                fingerprint: cameraFingerprint(file),
                createdUtc: indexed!.createdUtc,
                durationSec: indexed!.durationSec,
                records: [],
                fingerprintTz: null,
                parseFilenameLocalTime: classifyFilenameTime,
                preciseFilenameOffsetSec: null,
                embeddedStartUtcHint: null,
                isTimelapse: false,
                wallDurationSec: null,
            });
            expect(result.source).toBe("mp4");
            expect(result.startUtc).toBe(Date.UTC(2026, 7, 9, 18, 23, 34) / 1000);
        } finally {
            process.env.TZ = previousTz;
        }
    });

    it("keeps the genuine status-only freeGPS markers without producing a GPS format", async () => {
        const file = loadFixture();
        const index = await buildMp4Index(file.file);
        expect(index.hasFreeGpsMarker).toBe(true);
        expect(await freegpsPrimitive.marker(file, index)).toBe(true);
        await expect(freegpsPrimitive.parse(file, index)).rejects.toBeInstanceOf(WrongFormatError);
    });
});
