// Generated by scripts/parser-cache-revisions.mjs. Do not edit by hand.
// Revisions hash tree-shaken runtime bundles, including external package code.

export const VIDEO_EMBEDDED_DISPATCH_CACHE_REVISION = "97738c10da87d449";

export const VIDEO_EMBEDDED_PRIMITIVE_CACHE_REVISIONS = [
    { id: "rvmi", revision: "f897bdc7b93b6464" },
    { id: "sei-double-gps", revision: "566ef9319d2c7c02" },
    { id: "free-gps-box", revision: "ec627bdf59910f90" },
    { id: "ligogps", revision: "f970928494bd7cb2" },
    { id: "navitel-tail", revision: "2560aaa9167a2f4b" },
    { id: "autovox-riff", revision: "f184501eae8c99f3" },
    { id: "gps-box-70mai", revision: "09d52c5f4100a2ff" },
    { id: "garmin-uuid", revision: "5d99ca00ba711a9d" },
    { id: "ligo-json", revision: "e9d1a330447aa8d1" },
    { id: "kenwood", revision: "322e0cb2967a5bfc" },
    { id: "ligogps-trailer", revision: "5ef09d3ac1ddd502" },
    { id: "gpslog-atom", revision: "fc5afbf61ea2e86b" },
    { id: "nextbase-gdat", revision: "80e0277ea7adb6ea" },
    { id: "gpmf", revision: "d58eb6e4f7e0a841" },
    { id: "wolfbox-gpmd", revision: "e22a3d109509ca6c" },
    { id: "vantrue-fmas", revision: "8e6b89b5de9f9a45" },
    { id: "rove-gpmd", revision: "c9a84a77f7c8af5f" },
    { id: "rove-ssmd", revision: "dfc51d2b7ac4306a" },
    { id: "sstar-ssmd", revision: "a7ff581e0d11d024" },
    { id: "vueroid-txet", revision: "a5230c52886aa5fe" },
    { id: "pndm", revision: "3bdb35c73aaf8994" },
    { id: "nextbase-subtitle", revision: "7a75963a7bdca1f7" },
    { id: "nmea-subtitle", revision: "ce44d94af02c5382" },
    { id: "gpslog-atom-nbmt", revision: "16151db75975bf5e" },
    { id: "juscar-ts", revision: "d718013265e98d73" },
    { id: "ligogps-trailer-ts", revision: "5b4075e3d4208c6c" },
    { id: "novatek-ts", revision: "6f81b4dd9e800a41" },
    { id: "ts-pes-gps", revision: "2d3e8c6877765768" },
    { id: "freegps-70mai", revision: "b7b9702481621362" },
    { id: "freegps", revision: "ee7bc02ff4de4f4f" },
] as const;
