// Generated by scripts/parser-cache-revisions.mjs. Do not edit by hand.
// Revisions hash the normalized AST of tree-shaken runtime bundles, including external package code.

export const VIDEO_EMBEDDED_DISPATCH_CACHE_REVISION = "78ae770dc83703df";

export const VIDEO_EMBEDDED_PRIMITIVE_CACHE_REVISIONS = [
    { id: "rvmi", revision: "8d873cfbdff71179" },
    { id: "sei-double-gps", revision: "1fd70b1bd57bf5f4" },
    { id: "free-gps-box", revision: "16163467b31774e0" },
    { id: "ligogps", revision: "967ff5ee0f39fe48" },
    { id: "navitel-tail", revision: "761e2f2dbfb9c4ac" },
    { id: "autovox-riff", revision: "6d194350f10350d7" },
    { id: "gps-box-70mai", revision: "870c3842dbec9816" },
    { id: "garmin-uuid", revision: "ae816b058128f602" },
    { id: "ligo-json", revision: "1de83d5110dd86d7" },
    { id: "kenwood", revision: "3a9fd5d001243f1d" },
    { id: "ligogps-trailer", revision: "f4f185c9f1f07a56" },
    { id: "gpslog-atom", revision: "076fff6fce5299bd" },
    { id: "nextbase-gdat", revision: "af08f1dbc6442eaf" },
    { id: "gpmf", revision: "8337854a2139e0d6" },
    { id: "wolfbox-gpmd", revision: "f700573a5417339f" },
    { id: "vantrue-fmas", revision: "fa7437366e0752b0" },
    { id: "rove-gpmd", revision: "44fc4460ff4eeff4" },
    { id: "rove-ssmd", revision: "ec2837dcae4be7f6" },
    { id: "sstar-ssmd", revision: "1094338c62aeb735" },
    { id: "vueroid-txet", revision: "a802ebb2594b1762" },
    { id: "pndm", revision: "4aa30daf3ba07a0e" },
    { id: "nextbase-subtitle", revision: "526dc49c222439d7" },
    { id: "nmea-subtitle", revision: "74130854cfd0a66a" },
    { id: "gpslog-atom-nbmt", revision: "9db956c0346de341" },
    { id: "juscar-ts", revision: "a1ad7e7333ca00f3" },
    { id: "ligogps-trailer-ts", revision: "10f306f830df2d1b" },
    { id: "novatek-ts", revision: "4a49db40faa0b875" },
    { id: "ts-pes-gps", revision: "af8fd5a07f295fdb" },
    { id: "freegps-70mai", revision: "760a451c2c37a5e4" },
    { id: "freegps", revision: "47e02c28b198157e" },
] as const;
