// Generated by scripts/parser-cache-revisions.mjs. Do not edit by hand.
// Revisions hash tree-shaken runtime bundles, including external package code.

export const VIDEO_EMBEDDED_DISPATCH_CACHE_REVISION = "e2412cd695260fd7";

export const VIDEO_EMBEDDED_PRIMITIVE_CACHE_REVISIONS = [
    { id: "rvmi", revision: "5209e65ff7f67856" },
    { id: "free-gps-box", revision: "ceddb901ebba6cfc" },
    { id: "ligogps", revision: "5d3bfcdee2fbe35e" },
    { id: "navitel-tail", revision: "b1ea110bbfcfc919" },
    { id: "autovox-riff", revision: "f184501eae8c99f3" },
    { id: "gps-box-70mai", revision: "09d52c5f4100a2ff" },
    { id: "garmin-uuid", revision: "5d99ca00ba711a9d" },
    { id: "ligo-json", revision: "a8598ff8d05aecad" },
    { id: "kenwood", revision: "a5d6579da5ace4eb" },
    { id: "ligogps-trailer", revision: "f4923707d2e5cd3e" },
    { id: "gpslog-atom", revision: "fc5afbf61ea2e86b" },
    { id: "nextbase-gdat", revision: "80e0277ea7adb6ea" },
    { id: "gpmf", revision: "030bb7a81a478d81" },
    { id: "wolfbox-gpmd", revision: "2e0b8ff8bff1309e" },
    { id: "vantrue-fmas", revision: "9481afb7efab8760" },
    { id: "rove-gpmd", revision: "848ee5d796e4aee2" },
    { id: "rove-ssmd", revision: "9898cecc4c124470" },
    { id: "sstar-ssmd", revision: "e8524fd268b72793" },
    { id: "vueroid-txet", revision: "cc488c7e2f3075ee" },
    { id: "pndm", revision: "fe492c1b83811af2" },
    { id: "nextbase-subtitle", revision: "3ad43e7acf455538" },
    { id: "nmea-subtitle", revision: "c2efe9ab1435ca7e" },
    { id: "gpslog-atom-nbmt", revision: "16151db75975bf5e" },
    { id: "juscar-ts", revision: "d718013265e98d73" },
    { id: "ligogps-trailer-ts", revision: "fc2dfe57112980aa" },
    { id: "novatek-ts", revision: "2f23a66b7a05ef5b" },
    { id: "ts-pes-gps", revision: "b01e8bb18ca5e2f7" },
    { id: "freegps-70mai", revision: "2e6257db1c5b904a" },
    { id: "freegps", revision: "da32b9b7c8890115" },
] as const;
