import { SAMPLE_70MAI, boxOf, loadTrip, masterVideoTime, pausePlayback, presetLocalStorage } from "../e2e/_fixtures.js";
import { expect } from "@playwright/test";

import { openPortable, test } from "./_fixtures.js";

test("file playback keeps its context and remembers panels below the video after reload", async ({ page }, info) => {
    await presetLocalStorage(page);
    await page.addInitScript(() => {
        localStorage.setItem("dashcamigo:hotkeys:seekStepSec", "0.5");
        Object.defineProperty(Element.prototype, "requestFullscreen", { configurable: true, value: undefined });
        Object.defineProperty(Document.prototype, "fullscreenEnabled", { configurable: true, get: () => false });
        window.addEventListener("dc:ready", () => window.__dashcamigo.setMapProvider("route-only"), { once: true });
    });
    const url = await openPortable(page, info.outputPath("fullscreen"));
    expect(url).toMatch(/^file:/);
    await loadTrip(page, SAMPLE_70MAI);
    await pausePlayback(page);
    await page.locator(".top-panel__audio-select").selectOption("rear");
    await page.locator("#player-mini-progress").focus();
    await page.keyboard.press("Home");
    await expect.poll(() => masterVideoTime(page)).toBeLessThan(0.1);
    await page.keyboard.press("ArrowRight");
    await expect.poll(() => masterVideoTime(page)).toBeCloseTo(0.5, 1);
    const time = await masterVideoTime(page);
    const composition = await page.evaluate(() => window.__dashcamigo.state.composition);
    const player = page.locator("#player-wrap");
    await page.locator("#player-fullscreen").click();
    await expect(player).toHaveClass(/player-expanded/);
    await expect(player).not.toHaveClass(/player-panels-below/);
    await page.locator("#player-view-menu").click();
    const option = page.locator("[data-fullscreen-panels-below]");
    await expect(option).toHaveAttribute("aria-checked", "false");
    await option.click();
    await expect(option).toHaveAttribute("aria-checked", "true");
    await page.keyboard.press("Escape");
    await expect(player).toHaveClass(/player-panels-below/);
    const frame = await boxOf(page, ".video-frame");
    const timeline = await boxOf(page, "#player-chart");
    expect(timeline.y).toBeGreaterThanOrEqual(frame.y + frame.height - 1);
    await expect(page.locator("#player-controls-pin")).toBeHidden();
    await expect(page.locator("#player-play")).toHaveAttribute("data-paused", "true");
    expect(await masterVideoTime(page)).toBeCloseTo(time, 2);
    expect(await page.evaluate(() => window.__dashcamigo.state.composition)).toEqual(composition);
    await page.keyboard.press("Escape");
    await expect(player).not.toHaveClass(/player-expanded|player-panels-below/);
    await expect(page.locator("#player-fullscreen")).toBeFocused();
    expect(await masterVideoTime(page)).toBeCloseTo(time, 2);
    await page.locator("#player-fullscreen").click();
    await expect(player).toHaveClass(/player-panels-below/);
    await page.locator("#player-fullscreen-exit").click();
    await expect(player).not.toHaveClass(/player-expanded/);
    expect(await page.evaluate(() => window.__dashcamigo.state.composition)).toEqual(composition);
    await page.reload();
    await expect(page).toHaveURL(url);
    await loadTrip(page, SAMPLE_70MAI);
    await pausePlayback(page);
    await page.locator("#player-fullscreen").click();
    await expect(player).toHaveClass(/player-panels-below/);
    await page.locator("#player-view-menu").click();
    await expect(option).toHaveAttribute("aria-checked", "true");
    await page.keyboard.press("Escape");
    await page.locator("#player-fullscreen-exit").click();
    await expect(player).not.toHaveClass(/player-expanded/);
});
