// Generated by scripts/parser-cache-revisions.mjs. Do not edit by hand.
// Covers the tree-shaken metadata producer, including external package code.

export const RECORDING_METADATA_CACHE_REVISION = "1dd7d9c0aad20c54";
