// Generated by scripts/parser-cache-revisions.mjs. Do not edit by hand.
// Covers the tree-shaken metadata producer, including external package code.

export const RECORDING_METADATA_CACHE_REVISION = "c4cec6e36f18e8e6";
