// Generated by scripts/parser-cache-revisions.mjs. Do not edit by hand.
// Hashes the normalized AST of the tree-shaken metadata producer, including external package code.

export const RECORDING_METADATA_CACHE_REVISION = "6e34bdafd4c9e91c";
