// User-facing changelog: the single source of truth for the in-app "What's
// new" modal, the generated CHANGELOG.md and the GitHub release notes
// (scripts/generate-changelog-md.mjs / generate-release-notes.mjs). Entries
// are coarse outcome statements a driver cares about - never commit-level
// detail; wording follows .claude/rules/voice.md. Maintained by the changelog
// skill (.claude/skills/changelog/SKILL.md), newest first.
//
// Texts live here as data, NOT as I18nKey entries: the dictionary is baked
// into every prerendered page's i18n island, so routing the ever-growing
// changelog history through it would bloat every page. This module is loaded
// lazily by the modal; the entry bundle only carries latest.ts for the badge.
// No runtime imports - scripts import this file under Node type stripping.

import type { Lang } from "../i18n/index.js";

/** What kind of change an entry announces; drives the icon in the modal and
 *  the group label in the generated markdown. */
export type ChangelogCategory = "support" | "feature" | "improvement" | "fix";

export interface ChangelogEntry {
    /** "<yyyy-mm-dd>.<n>" - see src/changelog/id.ts for the contract. */
    id: string;
    category: ChangelogCategory;
    /** One coarse sentence per locale. English is the source of truth for
     *  meaning (voice.md); the markdown generators emit the English text. */
    text: Record<Lang, string>;
}

export const CHANGELOG_ENTRIES: readonly ChangelogEntry[] = [
    {
        id: "2026-08-29.2",
        category: "improvement",
        text: {
            en: "Improved storage and synchronization of trip notes, favorites, and markers.",
            ru: "Улучшены хранение и синхронизация заметок, избранного и маркеров.",
            de: "Die Speicherung und Synchronisierung von Fahrtnotizen, Favoriten und Markierungen wurde verbessert.",
            es: "Se han mejorado el almacenamiento y la sincronización de notas de viaje, favoritos y marcadores.",
            fr: "Le stockage et la synchronisation des notes de trajet, des favoris et des marqueurs ont été améliorés.",
            pl: "Ulepszono przechowywanie i synchronizację notatek z przejazdów, ulubionych i znaczników.",
            pt: "O armazenamento e a sincronização de notas de viagem, favoritos e marcadores foram aprimorados.",
            zh: "改进了行程备注、收藏和标记的存储与同步方式。",
            ja: "走行メモ、お気に入り、マーカーの保存と同期方法を改善しました。",
            ko: "주행 메모, 즐겨찾기, 마커의 저장 및 동기화 방식을 개선했습니다.",
        },
    },
    {
        id: "2026-08-29.1",
        category: "feature",
        text: {
            en: "Map markers can now use different vehicles, colors, and sizes.",
            ru: "Для маркера на карте теперь можно выбрать транспорт, цвет и размер.",
            de: "Kartenmarker können jetzt verschiedene Fahrzeuge, Farben und Größen verwenden.",
            es: "Los marcadores del mapa ahora pueden usar distintos vehículos, colores y tamaños.",
            fr: "Les marqueurs de carte peuvent désormais utiliser différents véhicules, couleurs et tailles.",
            pl: "Znaczniki na mapie mogą teraz przedstawiać różne pojazdy oraz mieć różne kolory i rozmiary.",
            pt: "Os marcadores do mapa agora podem usar diferentes veículos, cores e tamanhos.",
            zh: "现在可以为地图标记选择不同的车辆、颜色和大小。",
            ja: "マップマーカーで車種、色、サイズを選べるようになりました。",
            ko: "이제 지도 마커의 차량 종류, 색상, 크기를 선택할 수 있습니다.",
        },
    },
    {
        id: "2026-08-28.2",
        category: "fix",
        text: {
            en: "Zoomed charts now show a button to return to the full timeline.",
            ru: "После увеличения графика теперь видна кнопка возврата ко всей шкале времени.",
            de: "Vergrößerte Diagramme zeigen jetzt eine Schaltfläche zur Rückkehr zur vollständigen Zeitleiste.",
            es: "Los gráficos ampliados ahora muestran un botón para volver a la línea de tiempo completa.",
            fr: "Les graphiques agrandis affichent désormais un bouton pour revenir à la chronologie complète.",
            pl: "Powiększone wykresy mają teraz przycisk powrotu do pełnej osi czasu.",
            pt: "Os gráficos ampliados agora mostram um botão para voltar à linha do tempo completa.",
            zh: "图表缩放后现在会显示返回完整时间轴的按钮。",
            ja: "グラフを拡大すると、タイムライン全体に戻るボタンが表示されるようになりました。",
            ko: "이제 차트를 확대하면 전체 타임라인으로 돌아가는 버튼이 표시됩니다.",
        },
    },
    {
        id: "2026-08-28.1",
        category: "feature",
        text: {
            en: "GPX tracks can now be previewed before assigning them to trips.",
            ru: "GPX-треки теперь можно просмотреть перед привязкой к поездкам.",
            de: "GPX-Tracks können jetzt vor der Zuordnung zu Fahrten in einer Vorschau angezeigt werden.",
            es: "Ahora se pueden previsualizar los tracks GPX antes de asignarlos a trayectos.",
            fr: "Les traces GPX peuvent désormais être prévisualisées avant leur attribution aux trajets.",
            pl: "Ślady GPX można teraz podejrzeć przed przypisaniem ich do przejazdów.",
            pt: "Os trajetos GPX agora podem ser visualizados antes de serem associados a viagens.",
            zh: "现在可以在将 GPX 轨迹分配给行程前预览轨迹。",
            ja: "GPX 軌跡を走行に割り当てる前にプレビューできるようになりました。",
            ko: "이제 GPX 트랙을 주행에 연결하기 전에 미리 볼 수 있습니다.",
        },
    },
    {
        id: "2026-08-27.3",
        category: "improvement",
        text: {
            en: "Improved GPS sync.",
            ru: "Улучшена синхронизация GPS.",
            de: "Die GPS-Synchronisierung wurde verbessert.",
            es: "Se ha mejorado la sincronización GPS.",
            fr: "La synchronisation GPS a été améliorée.",
            pl: "Ulepszono synchronizację GPS.",
            pt: "A sincronização GPS foi aprimorada.",
            zh: "改进了 GPS 同步。",
            ja: "GPS 同期を改善しました。",
            ko: "GPS 동기화를 개선했습니다.",
        },
    },
    {
        id: "2026-08-27.2",
        category: "fix",
        text: {
            en: "HEVC recordings no longer show as unsupported when the browser can play them.",
            ru: "Записи HEVC больше не помечаются как неподдерживаемые, если браузер может их воспроизвести.",
            de: "HEVC-Aufnahmen werden nicht mehr als nicht unterstützt angezeigt, wenn der Browser sie abspielen kann.",
            es: "Las grabaciones HEVC ya no aparecen como no compatibles cuando el navegador puede reproducirlas.",
            fr: "Les enregistrements HEVC ne sont plus indiqués comme incompatibles lorsque le navigateur peut les lire.",
            pl: "Nagrania HEVC nie są już oznaczane jako nieobsługiwane, jeśli przeglądarka może je odtworzyć.",
            pt: "As gravações HEVC não aparecem mais como incompatíveis quando o navegador consegue reproduzi-las.",
            zh: "浏览器能够播放的 HEVC 录像不再显示为不受支持。",
            ja: "ブラウザで再生できる HEVC 録画が、非対応と表示されなくなりました。",
            ko: "브라우저에서 재생할 수 있는 HEVC 녹화가 더 이상 지원되지 않는 것으로 표시되지 않습니다.",
        },
    },
    {
        id: "2026-08-27.1",
        category: "support",
        text: {
            en: "Recordings from Botslab G300H, JOOYFACT A1, MiVue 955WD Pro, and similar models are now supported.",
            ru: "Записи Botslab G300H, JOOYFACT A1, MiVue 955WD Pro и схожих моделей теперь поддерживаются.",
            de: "Aufnahmen von Botslab G300H, JOOYFACT A1, MiVue 955WD Pro und ähnlichen Modellen werden jetzt unterstützt.",
            es: "Ahora se admiten grabaciones de Botslab G300H, JOOYFACT A1, MiVue 955WD Pro y modelos similares.",
            fr: "Les enregistrements des Botslab G300H, JOOYFACT A1, MiVue 955WD Pro et modèles similaires sont désormais pris en charge.",
            pl: "Nagrania z Botslab G300H, JOOYFACT A1, MiVue 955WD Pro i podobnych modeli są teraz obsługiwane.",
            pt: "Agora há suporte para gravações da Botslab G300H, JOOYFACT A1, MiVue 955WD Pro e modelos semelhantes.",
            zh: "现在支持 Botslab G300H、JOOYFACT A1、MiVue 955WD Pro 及类似型号的录像。",
            ja: "Botslab G300H、JOOYFACT A1、MiVue 955WD Pro、および同様のモデルの録画に対応しました。",
            ko: "이제 Botslab G300H, JOOYFACT A1, MiVue 955WD Pro 및 유사 모델의 녹화를 지원합니다.",
        },
    },
    {
        id: "2026-08-26.1",
        category: "feature",
        text: {
            en: "Multiple GPX tracks can now be matched to individual clips.",
            ru: "Несколько GPX-треков теперь можно сопоставить с отдельными фрагментами.",
            de: "Mehrere GPX-Tracks lassen sich jetzt einzelnen Clips zuordnen.",
            es: "Ahora se pueden asociar varios tracks GPX a clips individuales.",
            fr: "Plusieurs traces GPX peuvent désormais être associées à des clips individuels.",
            pl: "Wiele śladów GPX można teraz przypisać do poszczególnych klipów.",
            pt: "Vários trajetos GPX agora podem ser associados a clipes individuais.",
            zh: "现在可以将多个 GPX 轨迹分别匹配到各个片段。",
            ja: "複数の GPX 軌跡を個別のクリップに割り当てられるようになりました。",
            ko: "이제 여러 GPX 트랙을 개별 클립에 연결할 수 있습니다.",
        },
    },
    {
        id: "2026-08-24.1",
        category: "support",
        text: {
            en: "Sony HDR-AS30V recordings now show their GPS track and speed.",
            ru: "Записи Sony HDR-AS30V теперь показывают GPS-трек и скорость.",
            de: "Sony HDR-AS30V-Aufnahmen zeigen jetzt ihren GPS-Track und die Geschwindigkeit.",
            es: "Las grabaciones de la Sony HDR-AS30V ahora muestran su track GPS y la velocidad.",
            fr: "Les enregistrements Sony HDR-AS30V affichent désormais leur trace GPS et leur vitesse.",
            pl: "Nagrania z Sony HDR-AS30V pokazują teraz ślad GPS i prędkość.",
            pt: "As gravações da Sony HDR-AS30V agora mostram o trajeto GPS e a velocidade.",
            zh: "Sony HDR-AS30V 录像现在可以显示 GPS 轨迹和速度。",
            ja: "Sony HDR-AS30V の録画で GPS 軌跡と速度が表示されるようになりました。",
            ko: "Sony HDR-AS30V 녹화가 이제 GPS 트랙과 속도를 표시합니다.",
        },
    },
    {
        id: "2026-08-23.4",
        category: "feature",
        text: {
            en: "GPS tracks can now be synced with video separately for each trip.",
            ru: "GPS-треки теперь можно синхронизировать с видео отдельно для каждой поездки.",
            de: "GPS-Tracks lassen sich jetzt für jede Fahrt einzeln mit dem Video synchronisieren.",
            es: "Los tracks GPS ahora se pueden sincronizar con el vídeo por separado para cada trayecto.",
            fr: "Les traces GPS peuvent désormais être synchronisées avec la vidéo séparément pour chaque trajet.",
            pl: "Ślady GPS można teraz synchronizować z filmem osobno dla każdego przejazdu.",
            pt: "O trajeto GPS agora pode ser sincronizado com o vídeo separadamente em cada viagem.",
            zh: "现在可以为每个行程单独将 GPS 轨迹与视频同步。",
            ja: "走行ごとに GPS 軌跡を動画と個別に同期できるようになりました。",
            ko: "이제 주행마다 GPS 트랙을 영상과 개별적으로 동기화할 수 있습니다.",
        },
    },
    {
        id: "2026-08-23.3",
        category: "fix",
        text: {
            en: "Fullscreen now follows the selected theme.",
            ru: "Полноэкранный режим теперь следует выбранной теме.",
            de: "Der Vollbildmodus folgt jetzt dem ausgewählten Design.",
            es: "La pantalla completa ahora respeta el tema seleccionado.",
            fr: "Le mode plein écran respecte désormais le thème sélectionné.",
            pl: "Tryb pełnoekranowy korzysta teraz z wybranego motywu.",
            pt: "A tela cheia agora segue o tema selecionado.",
            zh: "全屏模式现在会使用所选主题。",
            ja: "フルスクリーンでも選択したテーマが使われるようになりました。",
            ko: "전체 화면에서도 이제 선택한 테마가 적용됩니다.",
        },
    },
    {
        id: "2026-08-23.2",
        category: "fix",
        text: {
            en: "Notes files no longer overwrite changes from other tabs or browser profiles.",
            ru: "Файлы пометок больше не перезаписывают изменения из других вкладок и профилей браузера.",
            de: "Notizdateien überschreiben keine Änderungen aus anderen Tabs oder Browserprofilen mehr.",
            es: "Los archivos de notas ya no sobrescriben cambios de otras pestañas o perfiles del navegador.",
            fr: "Les fichiers de notes n’écrasent plus les modifications d’autres onglets ou profils de navigateur.",
            pl: "Pliki notatek nie nadpisują już zmian z innych kart ani profili przeglądarki.",
            pt: "Os arquivos de notas não sobrescrevem mais alterações de outras abas ou perfis do navegador.",
            zh: "备注文件不再覆盖其他标签页或浏览器配置文件中的更改。",
            ja: "メモファイルが、ほかのタブやブラウザプロファイルの変更を上書きしなくなりました。",
            ko: "메모 파일이 더 이상 다른 탭이나 브라우저 프로필의 변경 사항을 덮어쓰지 않습니다.",
        },
    },
    {
        id: "2026-08-23.1",
        category: "improvement",
        text: {
            en: "More license plates are now found automatically.",
            ru: "Автоматический поиск теперь находит больше автомобильных номеров.",
            de: "Jetzt werden automatisch mehr Kennzeichen gefunden.",
            es: "Ahora se encuentran automáticamente más matrículas.",
            fr: "Davantage de plaques sont désormais détectées automatiquement.",
            pl: "Automatyczne wykrywanie znajduje teraz więcej tablic rejestracyjnych.",
            pt: "Agora mais placas são encontradas automaticamente.",
            zh: "现在可以自动找到更多车牌。",
            ja: "ナンバープレートを自動でより多く見つけられるようになりました。",
            ko: "이제 더 많은 번호판을 자동으로 찾습니다.",
        },
    },
    {
        id: "2026-08-22.3",
        category: "fix",
        text: {
            en: "Improved blur handling during export.",
            ru: "Улучшена работа зон скрытия при экспорте.",
            de: "Die Verarbeitung unkenntlich gemachter Bereiche beim Export wurde verbessert.",
            es: "Se ha mejorado el tratamiento de las zonas ocultas al exportar.",
            fr: "La gestion des zones masquées lors de l’export a été améliorée.",
            pl: "Ulepszono obsługę ukrywanych obszarów podczas eksportu.",
            pt: "O tratamento das áreas ocultas durante a exportação foi aprimorado.",
            zh: "改进了导出时对隐藏区域的处理。",
            ja: "エクスポート時の非表示エリアの処理を改善しました。",
            ko: "내보낼 때 가리는 영역의 처리를 개선했습니다.",
        },
    },
    {
        id: "2026-08-22.2",
        category: "improvement",
        text: {
            en: "Trips now appear before recording checks finish, with progress shown in the list.",
            ru: "Поездки теперь появляются до конца проверки записей, а прогресс виден в списке.",
            de: "Fahrten erscheinen jetzt schon vor Abschluss der Aufnahmeprüfung; der Fortschritt wird in der Liste angezeigt.",
            es: "Los trayectos ahora aparecen antes de que termine la comprobación de las grabaciones, con el progreso visible en la lista.",
            fr: "Les trajets apparaissent désormais avant la fin de la vérification des enregistrements, avec la progression affichée dans la liste.",
            pl: "Przejazdy pojawiają się teraz przed zakończeniem sprawdzania nagrań, a postęp jest widoczny na liście.",
            pt: "As viagens agora aparecem antes do fim da verificação das gravações, com o progresso exibido na lista.",
            zh: "录像检查完成前就会显示行程，列表中也会显示进度。",
            ja: "録画の確認が終わる前に走行が表示され、一覧で進行状況も確認できるようになりました。",
            ko: "녹화 확인이 끝나기 전부터 주행이 표시되며, 목록에서 진행 상황도 볼 수 있습니다.",
        },
    },
    {
        id: "2026-08-22.1",
        category: "fix",
        text: {
            en: "Renamed 70mai and Juscar recordings now keep their GPS tracks; invalid dates or coordinates are skipped instead of shifting the route.",
            ru: "Переименованные записи 70mai и Juscar теперь не теряют GPS-треки; некорректные даты и координаты пропускаются и больше не сдвигают маршрут.",
            de: "Umbenannte Aufnahmen von 70mai und Juscar behalten jetzt ihre GPS-Tracks; ungültige Datums- oder Koordinatenwerte werden übersprungen, statt die Route zu verschieben.",
            es: "Las grabaciones renombradas de 70mai y Juscar ahora conservan sus tracks GPS; las fechas o coordenadas no válidas se omiten en lugar de desplazar la ruta.",
            fr: "Les enregistrements 70mai et Juscar renommés conservent désormais leurs traces GPS ; les dates ou coordonnées invalides sont ignorées au lieu de décaler l’itinéraire.",
            pl: "Nagrania 70mai i Juscar po zmianie nazwy zachowują teraz ślad GPS; nieprawidłowe daty lub współrzędne są pomijane zamiast przesuwać trasę.",
            pt: "As gravações renomeadas da 70mai e Juscar agora mantêm o trajeto GPS; datas ou coordenadas inválidas são ignoradas em vez de deslocar a rota.",
            zh: "重命名后的 70mai 和 Juscar 录像现在仍会保留 GPS 轨迹；无效的日期或坐标会被跳过，不再导致路线偏移。",
            ja: "名前を変更した 70mai と Juscar の録画でも GPS 軌跡が維持され、無効な日時や座標はルートをずらさずにスキップされるようになりました。",
            ko: "이름을 바꾼 70mai 및 Juscar 녹화도 이제 GPS 트랙을 유지하며, 잘못된 날짜나 좌표는 경로를 어긋나게 하지 않고 건너뜁니다.",
        },
    },
    {
        id: "2026-08-21.1",
        category: "improvement",
        text: {
            en: "The map now switches to a backup source when the primary source is unavailable.",
            ru: "Если основной источник карты недоступен, карта теперь переключается на запасной.",
            de: "Die Karte wechselt jetzt auf eine Ersatzquelle, wenn die Hauptquelle nicht verfügbar ist.",
            es: "El mapa ahora cambia a una fuente alternativa cuando la principal no está disponible.",
            fr: "La carte passe désormais à une source de secours lorsque la source principale est indisponible.",
            pl: "Mapa przełącza się teraz na zapasowe źródło, gdy główne źródło jest niedostępne.",
            pt: "O mapa agora muda para uma fonte alternativa quando a principal está indisponível.",
            zh: "主要地图来源不可用时，现在会切换到备用来源。",
            ja: "メインの地図を利用できない場合、予備の地図に切り替わるようになりました。",
            ko: "기본 지도 서비스를 사용할 수 없으면 이제 대체 서비스로 전환합니다.",
        },
    },
    {
        id: "2026-08-19.1",
        category: "improvement",
        text: {
            en: "Localization has been improved.",
            ru: "Улучшена локализация.",
            de: "Die Lokalisierung wurde verbessert.",
            es: "Se ha mejorado la localización.",
            fr: "La localisation a été améliorée.",
            pl: "Ulepszono lokalizację.",
            pt: "A localização foi aprimorada.",
            zh: "改进了本地化。",
            ja: "ローカライズを改善しました。",
            ko: "현지화를 개선했습니다.",
        },
    },
    {
        id: "2026-08-18.2",
        category: "fix",
        text: {
            en: "RedTiger and FitCamX two-camera recordings now join the front and rear cameras into one trip instead of two separate ones.",
            ru: "Записи двухкамерных RedTiger и FitCamX теперь объединяют переднюю и заднюю камеры в одну поездку — вместо двух отдельных.",
            de: "Aufnahmen von RedTiger- und FitCamX-Zweikamera-Setups fassen Front- und Heckkamera jetzt in einer Fahrt zusammen statt in zwei getrennten.",
            es: "Las grabaciones de dos cámaras de RedTiger y FitCamX ahora unen la cámara frontal y la trasera en un solo trayecto en lugar de dos separados.",
            fr: "Les enregistrements à deux caméras RedTiger et FitCamX regroupent désormais les caméras avant et arrière dans un seul trajet au lieu de deux.",
            pl: "Nagrania z dwukamerowych zestawów RedTiger i FitCamX łączą teraz kamerę przednią i tylną w jeden przejazd zamiast dwóch osobnych.",
            pt: "As gravações de duas câmeras da RedTiger e FitCamX agora juntam as câmeras frontal e traseira em uma única viagem em vez de duas separadas.",
            zh: "RedTiger 和 FitCamX 双摄像头的录像现在会把前后摄像头合并为一个行程，而不是两个。",
            ja: "RedTiger と FitCamX の2カメラ録画は、前後のカメラが別々の走行ではなく1つの走行にまとまるようになりました。",
            ko: "RedTiger와 FitCamX 2카메라 녹화가 이제 전방·후방 카메라를 두 개가 아닌 하나의 주행으로 합칩니다.",
        },
    },
    {
        id: "2026-08-18.1",
        category: "support",
        text: {
            en: "Navitel recordings in .TS files now show their GPS track, with correct speed and direction.",
            ru: "Записи Navitel в .TS-файлах теперь показывают GPS-трек — с правильной скоростью и направлением.",
            de: "Navitel-Aufnahmen in .TS-Dateien zeigen jetzt ihren GPS-Track — mit korrekter Geschwindigkeit und Richtung.",
            es: "Las grabaciones de Navitel en archivos .TS ahora muestran su track GPS, con velocidad y dirección correctas.",
            fr: "Les enregistrements Navitel en fichiers .TS affichent désormais leur trace GPS, avec la vitesse et la direction correctes.",
            pl: "Nagrania Navitel w plikach .TS pokazują teraz ślad GPS — z poprawną prędkością i kierunkiem.",
            pt: "As gravações da Navitel em arquivos .TS agora mostram o trajeto GPS, com velocidade e direção corretas.",
            zh: "Navitel 的 .TS 录像现在可以显示 GPS 轨迹，速度和方向也是正确的。",
            ja: "Navitel の .TS ファイルの録画で GPS 軌跡が表示されるようになり、速度と方向も正しくなりました。",
            ko: "Navitel의 .TS 녹화 파일이 이제 GPS 트랙을 표시하며, 속도와 방향도 정확합니다.",
        },
    },
    {
        id: "2026-08-15.4",
        category: "fix",
        text: {
            en: "Picking a whole memory card or drive now shows it as one source with its real name.",
            ru: "Выбор целой карты памяти или диска теперь отображается как один источник с настоящим именем.",
            de: "Die Auswahl einer ganzen Speicherkarte oder eines Laufwerks erscheint jetzt als eine Quelle mit richtigem Namen.",
            es: "Al elegir una tarjeta de memoria o unidad entera, ahora aparece como una sola fuente con su nombre real.",
            fr: "Choisir une carte mémoire ou un disque entier apparaît désormais comme une seule source avec son vrai nom.",
            pl: "Wybór całej karty pamięci lub dysku pokazuje się teraz jako jedno źródło z prawdziwą nazwą.",
            pt: "Escolher um cartão de memória ou uma unidade inteira agora aparece como uma única fonte com o nome real.",
            zh: "选择整张存储卡或整个磁盘时，现在会显示为一个来源，并带有真实名称。",
            ja: "メモリーカードやドライブ全体を選んだとき、正しい名前の1つのソースとして表示されるようになりました。",
            ko: "메모리 카드나 드라이브 전체를 선택하면 이제 실제 이름을 가진 하나의 소스로 표시됩니다.",
        },
    },
    {
        id: "2026-08-15.3",
        category: "improvement",
        text: {
            en: "When a video can't be played in your browser (often HEVC on Windows), the player now explains why and shows how to fix it.",
            ru: "Если видео не проигрывается в браузере (чаще всего HEVC на Windows), плеер теперь объясняет причину и подсказывает, как это исправить.",
            de: "Wenn dein Browser ein Video nicht abspielen kann (oft HEVC unter Windows), erklärt der Player jetzt den Grund und zeigt, wie du es behebst.",
            es: "Si tu navegador no puede reproducir un vídeo (a menudo HEVC en Windows), el reproductor ahora explica el motivo y muestra cómo solucionarlo.",
            fr: "Si ton navigateur ne peut pas lire une vidéo (souvent HEVC sous Windows), le lecteur explique désormais pourquoi et montre comment y remédier.",
            pl: "Jeśli przeglądarka nie może odtworzyć wideo (często HEVC w Windows), odtwarzacz wyjaśnia teraz przyczynę i pokazuje, jak to naprawić.",
            pt: "Se o navegador não consegue reproduzir um vídeo (muitas vezes HEVC no Windows), o player agora explica o motivo e mostra como resolver.",
            zh: "当浏览器无法播放某个视频时（在 Windows 上常见于 HEVC），播放器现在会说明原因并告诉你如何解决。",
            ja: "ブラウザで動画を再生できないとき（Windows の HEVC でよくあります）、プレーヤーが理由と対処方法を表示するようになりました。",
            ko: "브라우저에서 영상을 재생할 수 없을 때(Windows의 HEVC에서 흔함), 플레이어가 이제 원인과 해결 방법을 알려줍니다.",
        },
    },
    {
        id: "2026-08-15.2",
        category: "fix",
        text: {
            en: "Fixed false speed spikes on the speed chart for 70mai 4K (A810, M500).",
            ru: "Починены ложные всплески скорости на графике для 70mai 4K (A810, M500).",
            de: "Falsche Geschwindigkeitsspitzen im Diagramm für 70mai 4K (A810, M500) behoben.",
            es: "Arreglados los picos falsos de velocidad en la gráfica para las 70mai 4K (A810, M500).",
            fr: "Correction des pics de vitesse erronés sur la courbe pour les 70mai 4K (A810, M500).",
            pl: "Naprawione fałszywe skoki prędkości na wykresie dla 70mai 4K (A810, M500).",
            pt: "Corrigidos os picos falsos de velocidade no gráfico para as 70mai 4K (A810, M500).",
            zh: "修复了 70mai 4K（A810、M500）速度图表上的虚假速度突刺。",
            ja: "70mai 4K（A810、M500）の速度グラフに出る誤ったスパイクを修正しました。",
            ko: "70mai 4K(A810, M500)의 속도 차트에 나타나던 잘못된 속도 급등을 고쳤습니다.",
        },
    },
    {
        id: "2026-08-15.1",
        category: "feature",
        text: {
            en: "Street and place names on the map are now adjustable — a gear right on the map sets the text size and how many street names to show.",
            ru: "Названия улиц и мест на карте теперь настраиваются — шестерёнка прямо на карте задаёт размер надписей и количество названий улиц.",
            de: "Straßen- und Ortsnamen auf der Karte lassen sich jetzt einstellen — ein Zahnrad direkt auf der Karte regelt die Textgröße und wie viele Straßennamen angezeigt werden.",
            es: "Los nombres de calles y lugares en el mapa ahora se pueden ajustar: una rueda dentada en el propio mapa controla el tamaño del texto y cuántos nombres de calles mostrar.",
            fr: "Les noms de rues et de lieux sur la carte se règlent désormais — un engrenage directement sur la carte ajuste la taille du texte et le nombre de noms de rues affichés.",
            pl: "Nazwy ulic i miejsc na mapie można teraz dostosować — zębatka bezpośrednio na mapie ustawia rozmiar tekstu i liczbę wyświetlanych nazw ulic.",
            pt: "Os nomes de ruas e lugares no mapa agora são ajustáveis — uma engrenagem no próprio mapa define o tamanho do texto e quantos nomes de ruas mostrar.",
            zh: "地图上的街道和地名现在可以调节了——地图上的齿轮按钮可设置文字大小和街道名称的显示数量。",
            ja: "地図の通り名・地名を調整できるようになりました。地図上の歯車ボタンで、文字サイズと通り名の表示量を設定できます。",
            ko: "지도의 거리·장소 이름을 이제 조절할 수 있습니다. 지도 위의 톱니바퀴 버튼으로 글자 크기와 표시할 거리 이름 개수를 설정합니다.",
        },
    },
    {
        id: "2026-08-14.2",
        category: "fix",
        text: {
            en: "Fixed playback of some kinds of .ts recordings.",
            ru: "Полечено проигрывание некоторых видов .ts-файлов.",
            de: "Wiedergabe einiger Arten von .ts-Dateien repariert.",
            es: "Arreglada la reproducción de algunos tipos de archivos .ts.",
            fr: "Lecture de certains types de fichiers .ts réparée.",
            pl: "Naprawione odtwarzanie niektórych rodzajów plików .ts.",
            pt: "Corrigida a reprodução de alguns tipos de arquivos .ts.",
            zh: "修复了某些 .ts 文件的播放问题。",
            ja: "一部の .ts ファイルの再生を修正しました。",
            ko: "일부 .ts 파일의 재생 문제를 고쳤습니다.",
        },
    },
    {
        id: "2026-08-14.1",
        category: "support",
        text: {
            en: "Added support for new recording folder and file layouts.",
            ru: "Добавлена поддержка новых форматов файловой структуры записей.",
            de: "Unterstützung für neue Ordner- und Dateistrukturen von Aufnahmen hinzugefügt.",
            es: "Añadido soporte para nuevas estructuras de carpetas y archivos de grabaciones.",
            fr: "Prise en charge de nouvelles structures de dossiers et de fichiers d'enregistrements ajoutée.",
            pl: "Dodana obsługa nowych układów folderów i plików nagrań.",
            pt: "Adicionado suporte a novas estruturas de pastas e arquivos de gravações.",
            zh: "新增支持更多录像文件与文件夹结构。",
            ja: "新しい録画のフォルダ・ファイル構成に対応しました。",
            ko: "새로운 녹화 폴더·파일 구조를 지원합니다.",
        },
    },
    {
        id: "2026-08-11.1",
        category: "fix",
        text: {
            en: "Fixed GPS for 70mai 4K cameras (A810, M500): routes were drawn tens of kilometers off to the side — open your folder again and the track lands on the road you actually drove.",
            ru: "Починен GPS у 70mai 4K (A810, M500): маршрут рисовался в десятках километров в стороне — открой папку заново, и трек ляжет на реальную дорогу.",
            de: "GPS bei 70mai-4K-Kameras (A810, M500) repariert: Die Route lag Dutzende Kilometer daneben — öffne den Ordner erneut, und die Strecke liegt auf der tatsächlich gefahrenen Straße.",
            es: "Arreglado el GPS de las 70mai 4K (A810, M500): la ruta se dibujaba a decenas de kilómetros de distancia — vuelve a abrir la carpeta y la traza cae sobre la carretera real.",
            fr: "GPS des 70mai 4K (A810, M500) réparé : le trajet était tracé à des dizaines de kilomètres à côté — rouvre le dossier et la trace retombe sur la vraie route.",
            pl: "Naprawiony GPS w kamerach 70mai 4K (A810, M500): trasa była rysowana dziesiątki kilometrów obok — otwórz folder ponownie, a ślad ułoży się na prawdziwej drodze.",
            pt: "GPS das 70mai 4K (A810, M500) corrigido: a rota era desenhada a dezenas de quilômetros de distância — abra a pasta de novo e o trajeto cai na estrada real.",
            zh: "修复了 70mai 4K（A810、M500）的 GPS：路线此前会偏移几十公里——重新打开文件夹，轨迹就会落在实际行驶的道路上。",
            ja: "70mai 4K（A810、M500）の GPS を修正しました。ルートが数十キロずれて描かれていましたが、フォルダを開き直せば実際に走った道路の上に軌跡が乗ります。",
            ko: "70mai 4K(A810, M500)의 GPS를 고쳤습니다. 경로가 수십 킬로미터 옆에 그려졌는데, 폴더를 다시 열면 실제로 달린 도로 위에 트랙이 표시됩니다.",
        },
    },
    {
        id: "2026-08-08.5",
        category: "fix",
        text: {
            en: "Right after an update rolls out, the app could get stuck reloading in a loop — now it waits a moment and picks up the new version cleanly.",
            ru: "Сразу после выхода обновления приложение могло застрять в бесконечной перезагрузке — теперь оно выжидает и спокойно подхватывает новую версию.",
            de: "Direkt nach einem Update konnte die App in einer Neuladeschleife hängen bleiben — jetzt wartet sie kurz und holt sich die neue Version sauber.",
            es: "Justo después de publicarse una actualización, la app podía quedarse recargando en bucle — ahora espera un momento y carga la versión nueva sin problemas.",
            fr: "Juste après la sortie d'une mise à jour, l'appli pouvait rester bloquée à se recharger en boucle — désormais elle patiente un instant et récupère la nouvelle version proprement.",
            pl: "Tuż po wydaniu aktualizacji aplikacja mogła utknąć w pętli przeładowań — teraz chwilę odczekuje i spokojnie wczytuje nową wersję.",
            pt: "Logo após sair uma atualização, o app podia ficar preso recarregando em loop — agora ele espera um instante e carrega a versão nova sem problemas.",
            zh: "更新刚发布时，应用可能陷入反复刷新的循环——现在它会稍等片刻，平稳加载新版本。",
            ja: "アップデート公開直後にアプリが再読み込みを繰り返して固まることがありました。今は少し待ってから、新しいバージョンをきちんと読み込みます。",
            ko: "업데이트 직후 앱이 새로고침을 반복하며 멈출 수 있었는데, 이제는 잠시 기다렸다가 새 버전을 깔끔하게 불러옵니다.",
        },
    },
    {
        id: "2026-08-08.4",
        category: "fix",
        text: {
            en: "Expanding the map in a narrow window — a foldable or a tablet in portrait — no longer hides the video: the trip list steps aside instead.",
            ru: "Развёрнутая карта в узком окне — на складном смартфоне или планшете в портрете — больше не прячет видео: вместо этого уступает место список поездок.",
            de: "Die aufgeklappte Karte in einem schmalen Fenster — Foldable oder Tablet im Hochformat — verdeckt das Video nicht mehr: stattdessen macht die Fahrtenliste Platz.",
            es: "Ampliar el mapa en una ventana estrecha — un plegable o una tablet en vertical — ya no oculta el vídeo: en su lugar se aparta la lista de trayectos.",
            fr: "Agrandir la carte dans une fenêtre étroite — pliable ou tablette en portrait — ne masque plus la vidéo : c'est la liste des trajets qui s'efface.",
            pl: "Rozwinięcie mapy w wąskim oknie — na składanym telefonie lub tablecie w pionie — nie zasłania już wideo: zamiast tego ustępuje lista przejazdów.",
            pt: "Expandir o mapa em uma janela estreita — um celular dobrável ou tablet na vertical — não esconde mais o vídeo: a lista de viagens é que dá lugar.",
            zh: "在窄窗口（折叠屏或竖屏平板）展开地图时，不再遮挡视频——改为收起行程列表。",
            ja: "折りたたみスマホや縦向きタブレットなど幅の狭い画面で地図を広げても、動画が隠れなくなりました。代わりに走行リストが一時的に隠れます。",
            ko: "폴더블이나 세로 태블릿처럼 좁은 창에서 지도를 펼쳐도 더 이상 영상이 가려지지 않습니다. 대신 주행 목록이 잠시 비켜납니다.",
        },
    },
    {
        id: "2026-08-08.3",
        category: "improvement",
        text: {
            en: "The folder warning on iPhone and iPad now points to the faster ways in — a computer, or copying the files you need into the Files app first.",
            ru: "Предупреждение о папках на iPhone и iPad теперь подсказывает пути побыстрее: компьютер — или сначала скопировать нужные файлы в приложение «Файлы».",
            de: "Der Ordner-Hinweis auf iPhone und iPad zeigt jetzt die schnelleren Wege — ein Computer, oder die benötigten Dateien zuerst in die Dateien-App kopieren.",
            es: "El aviso de carpetas en iPhone y iPad ahora sugiere las vías más rápidas: un ordenador, o copiar antes los archivos necesarios a la app Archivos.",
            fr: "L'avertissement de dossier sur iPhone et iPad indique désormais les voies plus rapides — un ordinateur, ou copier d'abord les fichiers utiles dans l'app Fichiers.",
            pl: "Ostrzeżenie o folderach na iPhonie i iPadzie podpowiada teraz szybsze drogi — komputer albo skopiowanie potrzebnych plików najpierw do aplikacji Pliki.",
            pt: "O aviso de pastas no iPhone e iPad agora aponta os caminhos mais rápidos — um computador, ou copiar antes os arquivos necessários para o app Arquivos.",
            zh: "iPhone 和 iPad 上的文件夹提示现在会指出更快的方式——用电脑，或先把所需文件复制到“文件”App。",
            ja: "iPhone・iPad のフォルダに関する案内が、より速い方法を示すようになりました。パソコンを使うか、必要なファイルを先に「ファイル」アプリへコピーする方法です。",
            ko: "iPhone과 iPad의 폴더 안내가 더 빠른 방법을 알려줍니다. 컴퓨터를 사용하거나, 필요한 파일을 먼저 '파일' 앱으로 복사하는 방법입니다.",
        },
    },
    {
        id: "2026-08-08.2",
        category: "feature",
        text: {
            en: "dashcamigo now tells you what's new — the sparkles button up top lights up when something fresh lands.",
            ru: "dashcamigo теперь рассказывает, что нового: кнопка с искрами сверху подсвечивается, когда появляется что-то свежее.",
            de: "dashcamigo zeigt jetzt, was neu ist — der Funkeln-Button oben leuchtet auf, wenn etwas Frisches ankommt.",
            es: "dashcamigo ahora te cuenta las novedades: el botón de destellos arriba se ilumina cuando llega algo nuevo.",
            fr: "dashcamigo te dit maintenant ce qui est nouveau — le bouton étincelles en haut s'allume quand du neuf arrive.",
            pl: "dashcamigo pokazuje teraz, co nowego — przycisk z iskierkami u góry podświetla się, gdy pojawi się coś świeżego.",
            pt: "O dashcamigo agora mostra as novidades — o botão de brilhos no topo acende quando chega algo novo.",
            zh: "dashcamigo 现在会告诉你有什么新变化——顶部的星光按钮在有新内容时会亮起。",
            ja: "dashcamigo が新着情報を知らせるようになりました。上部のキラキラボタンが、新しい変更があると光ります。",
            ko: "이제 dashcamigo가 새로운 소식을 알려줍니다. 상단의 반짝임 버튼이 새 변경이 있으면 켜집니다.",
        },
    },
    {
        id: "2026-08-08.1",
        category: "support",
        text: {
            en: "Beferich dashcams are now supported — the GPS track is read straight from the video files.",
            ru: "Поддержаны регистраторы Beferich — GPS-трек читается прямо из видеофайлов.",
            de: "Beferich-Dashcams werden jetzt unterstützt — der GPS-Track wird direkt aus den Videodateien gelesen.",
            es: "Ya hay soporte para las dashcams Beferich: el track GPS se lee directamente de los archivos de vídeo.",
            fr: "Les dashcams Beferich sont désormais prises en charge — la trace GPS est lue directement dans les fichiers vidéo.",
            pl: "Kamery Beferich są już obsługiwane — ślad GPS jest odczytywany prosto z plików wideo.",
            pt: "As dashcams Beferich agora são compatíveis — a trilha GPS é lida direto dos arquivos de vídeo.",
            zh: "现已支持 Beferich 行车记录仪——GPS 轨迹直接从视频文件中读取。",
            ja: "Beferich のドライブレコーダーに対応しました。GPS トラックは動画ファイルから直接読み取ります。",
            ko: "이제 Beferich 블랙박스를 지원합니다. GPS 트랙을 영상 파일에서 바로 읽어옵니다.",
        },
    },
    {
        id: "2026-08-07.1",
        category: "improvement",
        text: {
            en: "On iPhone and iPad, picking a folder now warns that it copies your recordings — and offers picking just the files you need.",
            ru: "На iPhone и iPad выбор папки теперь предупреждает, что записи будут скопированы, — и предлагает выбрать только нужные файлы.",
            de: "Auf iPhone und iPad warnt die Ordnerauswahl jetzt, dass sie deine Aufnahmen kopiert — und bietet an, nur die benötigten Dateien auszuwählen.",
            es: "En iPhone y iPad, elegir una carpeta ahora avisa de que copiará tus grabaciones y ofrece elegir solo los archivos que necesitas.",
            fr: "Sur iPhone et iPad, le choix d'un dossier prévient désormais qu'il copie tes enregistrements — et propose de ne choisir que les fichiers utiles.",
            pl: "Na iPhonie i iPadzie wybór folderu ostrzega teraz, że skopiuje nagrania — i proponuje wybranie tylko potrzebnych plików.",
            pt: "No iPhone e iPad, escolher uma pasta agora avisa que suas gravações serão copiadas — e oferece escolher só os arquivos necessários.",
            zh: "在 iPhone 和 iPad 上，选择文件夹时会提示将复制你的录像，并提供只选择所需文件的选项。",
            ja: "iPhone・iPad でフォルダを選ぶと、録画がコピーされることを事前に知らせ、必要なファイルだけ選ぶ方法も提案します。",
            ko: "iPhone과 iPad에서 폴더를 선택하면 녹화가 복사된다는 안내가 표시되고, 필요한 파일만 선택하는 방법도 제안합니다.",
        },
    },
    {
        id: "2026-08-04.3",
        category: "improvement",
        text: {
            en: "Trip names, notes and markers save to a notes file next to your recordings and load back on their own.",
            ru: "Названия поездок, заметки и маркеры сохраняются в файл заметок рядом с записями и подхватываются сами.",
            de: "Namen, Notizen und Marker von Fahrten werden in einer Notizdatei neben deinen Aufnahmen gespeichert und von selbst wieder geladen.",
            es: "Los nombres, notas y marcadores de los trayectos se guardan en un archivo de notas junto a tus grabaciones y se cargan solos.",
            fr: "Les noms, notes et marqueurs de trajets sont enregistrés dans un fichier de notes à côté de tes enregistrements et se rechargent tout seuls.",
            pl: "Nazwy, notatki i znaczniki przejazdów zapisują się w pliku notatek obok nagrań i same się wczytują.",
            pt: "Nomes, notas e marcadores das viagens são salvos em um arquivo de notas junto às gravações e carregados de volta sozinhos.",
            zh: "行程名称、笔记和标记会保存到录像旁的笔记文件中，并自动加载。",
            ja: "走行の名前・メモ・マーカーは録画と同じ場所のメモファイルに保存され、次回自動で読み込まれます。",
            ko: "주행 이름, 메모, 마커가 녹화 옆의 메모 파일에 저장되고 자동으로 다시 불러와집니다.",
        },
    },
    {
        id: "2026-08-04.2",
        category: "feature",
        text: {
            en: "Settings now show how much space the recordings cache takes — with a size limit and one-click clearing.",
            ru: "В настройках теперь видно, сколько места занимает кэш записей, — с лимитом размера и очисткой в один клик.",
            de: "Die Einstellungen zeigen jetzt, wie viel Platz der Aufnahmen-Cache belegt — mit Größenlimit und Leeren per Klick.",
            es: "Los ajustes ahora muestran cuánto espacio ocupa la caché de grabaciones, con límite de tamaño y borrado en un clic.",
            fr: "Les réglages montrent désormais l'espace occupé par le cache des enregistrements — avec une limite de taille et un vidage en un clic.",
            pl: "W ustawieniach widać teraz, ile miejsca zajmuje pamięć podręczna nagrań — z limitem rozmiaru i czyszczeniem jednym kliknięciem.",
            pt: "Os ajustes agora mostram quanto espaço o cache de gravações ocupa — com limite de tamanho e limpeza em um clique.",
            zh: "设置中现在可以看到录像缓存占用的空间——支持设置大小上限，一键清除。",
            ja: "設定で録画キャッシュの使用容量を確認できるようになりました。上限の指定もワンクリックでの削除もできます。",
            ko: "설정에서 녹화 캐시가 차지하는 공간을 확인할 수 있습니다. 크기 제한과 한 번의 클릭으로 비우기도 지원합니다.",
        },
    },
    {
        id: "2026-08-04.1",
        category: "feature",
        text: {
            en: "Speed, coordinates and GPS status get their own row under the player — hide it from the view menu if you don't need it.",
            ru: "Скорость, координаты и статус GPS — теперь отдельный ряд под плеером; спрятать его можно в меню «Вид».",
            de: "Tempo, Koordinaten und GPS-Status haben jetzt eine eigene Zeile unter dem Player — ausblendbar über das Ansicht-Menü.",
            es: "La velocidad, las coordenadas y el estado del GPS tienen su propia fila bajo el reproductor; se puede ocultar desde el menú Vista.",
            fr: "Vitesse, coordonnées et état GPS ont leur propre ligne sous le lecteur — masquable depuis le menu Vue.",
            pl: "Prędkość, współrzędne i stan GPS mają teraz własny wiersz pod odtwarzaczem — można go ukryć w menu widoku.",
            pt: "Velocidade, coordenadas e estado do GPS ganharam uma linha própria abaixo do player — dá para ocultar no menu Vista.",
            zh: "速度、坐标和 GPS 状态移到了播放器下方的独立一行——可在视图菜单中隐藏。",
            ja: "速度・座標・GPS の状態はプレーヤー下の専用行に移動しました。表示メニューから非表示にもできます。",
            ko: "속도, 좌표, GPS 상태가 플레이어 아래 전용 줄로 이동했습니다. 보기 메뉴에서 숨길 수 있습니다.",
        },
    },
];
