// Integration test for the CSP-hash pipeline. Reads the built artifacts
// (dist/index.html, dist/en/index.html, ..., dist/_headers) and asserts:
//
//   1. The inline <script id="dc-bootstrap"> body is byte-identical across
//      the root stub and every prerendered locale HTML. If they diverge,
//      one hash in CSP no longer covers all pages and at least one will
//      fail to boot in the browser - silent CSP rejection has no observable
//      symptom at build time, only at runtime.
//
//   2. The SHA-256 of that bootstrap body matches the 'sha256-...' value
//      spliced into dist/_headers by cspHashPlugin. Catches plugin-order
//      regressions: if rootStubPlugin runs AFTER cspHashPlugin, the stub's
//      bootstrap (or any future bootstrap edit between the two plugins)
//      would have a different hash than the one in _headers.
//
// This test runs against artifacts on disk - it requires `npm run build`
// to have been run first. When dist/ is missing the test is skipped locally
// (typical state of a fresh clone), but THROWS in CI: a silent skip there
// means the workflow ordered `npm test` before `npm run build` and this gate
// never ran at all - exactly the failure mode it exists to catch.

import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const DIST_DIR = resolve(__dirname, "..", "dist");
const ROOT_HTML = resolve(DIST_DIR, "index.html");
const HEADERS = resolve(DIST_DIR, "_headers");

// Read the inline <script id="dc-bootstrap">...</script> body. Mirrors the
// regex in vite-plugins/csp-hash.ts so any deviation between extractor and
// hasher would be caught.
const BOOTSTRAP_RE = /<script\b[^>]*\bid="dc-bootstrap"[^>]*>([\s\S]*?)<\/script>/;

function extractBootstrap(html: string): string {
    const m = BOOTSTRAP_RE.exec(html);
    if (!m) throw new Error('no <script id="dc-bootstrap"> in HTML');
    return m[1] ?? "";
}

// Recursively find every index.html under DIST_DIR. Includes the root stub
// and every locale's prerendered home plus the per-locale /cameras/ and
// /cameras/<slug>/ pages. Vendor pages do NOT carry an inline bootstrap
// (their HTML is generated by vendor-pages.ts with no <script id="dc-bootstrap">)
// - we filter to files that actually contain the bootstrap before asserting.
function findAllIndexHtml(dir: string, out: string[] = []): string[] {
    for (const entry of readdirSync(dir)) {
        const full = resolve(dir, entry);
        const st = statSync(full);
        if (st.isDirectory()) {
            findAllIndexHtml(full, out);
        } else if (entry === "index.html") {
            out.push(full);
        }
    }
    return out;
}

const hasDist = existsSync(ROOT_HTML) && existsSync(HEADERS);
// Fail-loud in CI: dist/ absent there means the workflow ran the unit tests
// before `npm run build` (see .github/workflows/ci.yml), and a silent skip
// would hide that this gate never executed. Locally a missing dist/ is the
// normal fresh-clone state, so the skip below keeps `npm test` green.
if (!hasDist && process.env.CI) {
    throw new Error(
        "csp-hash integration test: dist/index.html or dist/_headers missing in CI - run `npm run build` before `npm test`",
    );
}
// Without a built dist/ there is nothing to assert - skip (local dev only).
const itIf = hasDist ? it : it.skip;

describe("CSP hash integration: stub and locale pages share one bootstrap", () => {
    itIf("bootstrap script body is byte-identical across stub and every locale page that ships it", () => {
        const allHtml = findAllIndexHtml(DIST_DIR);
        expect(allHtml.length).toBeGreaterThan(1); // at least stub + /en/

        const bootstraps = new Map<string, string[]>(); // body -> files
        for (const file of allHtml) {
            const html = readFileSync(file, "utf-8");
            if (!BOOTSTRAP_RE.test(html)) continue; // vendor pages skip - no bootstrap
            const body = extractBootstrap(html);
            const list = bootstraps.get(body) ?? [];
            list.push(file);
            bootstraps.set(body, list);
        }

        expect(
            bootstraps.size,
            `expected one bootstrap body across all HTML, got ${bootstraps.size} distinct bodies:\n${[
                ...bootstraps.entries(),
            ]
                .map(([_body, files]) => `  - ${files.length} file(s): ${files[0]}`)
                .join("\n")}`,
        ).toBe(1);
    });

    itIf("the CSP sha256 in _headers matches the bootstrap body's actual SHA-256", () => {
        const stubHtml = readFileSync(ROOT_HTML, "utf-8");
        const body = extractBootstrap(stubHtml);
        const expectedHash = createHash("sha256").update(body, "utf-8").digest("base64");
        const expectedDirective = `'sha256-${expectedHash}'`;

        const headers = readFileSync(HEADERS, "utf-8");
        expect(
            headers,
            `_headers must contain ${expectedDirective} in script-src for the inline bootstrap to load`,
        ).toContain(expectedDirective);
    });
});
